import type { Language } from "@/context/AppContext";

export const APP_VERSION = "1.0.0";

export const SUPPORT_EMAILS = {
  general: "support@motoguard.app",
  safety: "safety@motoguard.app",
  features: "features@motoguard.app",
  privacy: "privacy@motoguard.app",
};

export const APP_STORE_URL = "https://apps.apple.com/app/motoguard";
export const PLAY_STORE_URL =
  "https://play.google.com/store/apps/details?id=com.motoguard.app";

export const RESPONSE_TIMES: Record<string, { label: string; color: string }> = {
  lifetime:  { label: "24h", color: "#22C55E" },
  pro_drone: { label: "24h", color: "#22C55E" },
  pro:       { label: "48h", color: "#3B82F6" },
  basic:     { label: "3 days", color: "#F59E0B" },
  free:      { label: "5 days", color: "#6B7280" },
};

export const SUPPORT_STRINGS: Record<Language, Record<string, string>> = {
  en: {
    title: "Support",
    responseTime: "Expected response time",
    bugTitle: "Report a Bug",
    bugSubtitle: "Experiencing a technical issue?",
    featureTitle: "Feature Request",
    featureSubtitle: "Vote on upcoming improvements",
    safetyTitle: "Safety Issue",
    safetySubtitle: "For critical safety-related bugs",
    faqTitle: "FAQ",
    faqSubtitle: "Quick answers to common questions",
    rateTitle: "Rate MotoGuard",
    rateSubtitle: "Help others discover the app",
    contactTitle: "Contact Us",
    contactSubtitle: "Send an email to our team",
    bugCategory: "Category",
    bugSummary: "Brief summary",
    bugSummaryPlaceholder: "What went wrong? (max 100 chars)",
    bugDescription: "Detailed description",
    bugDescriptionPlaceholder: "Steps to reproduce, what you expected vs what happened... (max 500 chars)",
    bugWhen: "When did it happen?",
    bugWhenPlaceholder: "e.g. Today at 14:35",
    bugSend: "Send Bug Report",
    safetyWarning: "⚠️ This option is exclusively for reporting critical bugs related to the app's safety functions (accident detection, emergency alerts). In a real emergency, call 112 or your local emergency number.",
    safetyIssueType: "What didn't work?",
    safetyDescription: "Description",
    safetyDescriptionPlaceholder: "Describe what happened in detail...",
    safetyWhen: "When did it happen?",
    safetySend: "Send Priority Report",
    featureVote: "Vote",
    featureVoted: "Voted ✓",
    featureStatusPlanned: "Planned",
    featureStatusInProgress: "In Progress 🔥",
    featureStatusCompleted: "Completed ✅",
    featureCustomTitle: "Have your own idea?",
    featureCustomPlaceholder: "Describe your feature idea...",
    featureCustomSend: "Submit Idea",
    back: "Back",
    send: "Send",
    cancel: "Cancel",
    charLeft: "chars left",
  },
  hu: {
    title: "Támogatás",
    responseTime: "Várható válaszidő",
    bugTitle: "Hiba bejelentése",
    bugSubtitle: "Technikai problémát tapasztal?",
    featureTitle: "Funkció kérése",
    featureSubtitle: "Szavazz a következő fejlesztésekre",
    safetyTitle: "Biztonsági probléma",
    safetySubtitle: "Kritikus biztonsági hiba esetén",
    faqTitle: "Gyakori kérdések",
    faqSubtitle: "Gyors válaszok a leggyakoribb kérdésekre",
    rateTitle: "Értékeld a MotoGuard-ot",
    rateSubtitle: "Segíts másoknak megtalálni az appot",
    contactTitle: "Kapcsolatfelvétel",
    contactSubtitle: "Küldj emailt a csapatunknak",
    bugCategory: "Kategória",
    bugSummary: "Rövid leírás",
    bugSummaryPlaceholder: "Mi nem működött? (max 100 karakter)",
    bugDescription: "Részletes leírás",
    bugDescriptionPlaceholder: "Reprodukálás lépései, mi volt várható vs mi történt... (max 500 karakter)",
    bugWhen: "Mikor történt?",
    bugWhenPlaceholder: "Pl. Ma 14:35-kor",
    bugSend: "Hibabejelentés küldése",
    safetyWarning: "⚠️ Ez az opció kizárólag az app biztonsági funkcióival (balesetdetekció, vészjelzés) kapcsolatos kritikus hibák bejelentésére szolgál. Valódi vészhelyzetben hívd a 112-t.",
    safetyIssueType: "Mi nem működött?",
    safetyDescription: "Leírás",
    safetyDescriptionPlaceholder: "Részletesen írd le mi történt...",
    safetyWhen: "Mikor történt?",
    safetySend: "Prioritásos bejelentés küldése",
    featureVote: "Szavazok",
    featureVoted: "Szavaztam ✓",
    featureStatusPlanned: "Tervezett",
    featureStatusInProgress: "Folyamatban 🔥",
    featureStatusCompleted: "Kész ✅",
    featureCustomTitle: "Saját ötleted van?",
    featureCustomPlaceholder: "Írd le a funkcióötleted...",
    featureCustomSend: "Ötlet beküldése",
    back: "Vissza",
    send: "Küldés",
    cancel: "Mégse",
    charLeft: "karakter maradt",
  },
  de: {
    title: "Support",
    responseTime: "Erwartete Antwortzeit",
    bugTitle: "Fehler melden",
    bugSubtitle: "Technisches Problem entdeckt?",
    featureTitle: "Funktion anfragen",
    featureSubtitle: "Stimme für kommende Verbesserungen",
    safetyTitle: "Sicherheitsproblem",
    safetySubtitle: "Für kritische Sicherheitsfehler",
    faqTitle: "Häufige Fragen",
    faqSubtitle: "Schnelle Antworten auf häufige Fragen",
    rateTitle: "MotoGuard bewerten",
    rateSubtitle: "Hilf anderen, die App zu finden",
    contactTitle: "Kontakt",
    contactSubtitle: "Sende eine E-Mail an unser Team",
    bugCategory: "Kategorie",
    bugSummary: "Kurzbeschreibung",
    bugSummaryPlaceholder: "Was ist schiefgelaufen? (max 100 Zeichen)",
    bugDescription: "Detaillierte Beschreibung",
    bugDescriptionPlaceholder: "Schritte zur Reproduktion, Erwartetes vs. Tatsächliches... (max 500 Zeichen)",
    bugWhen: "Wann ist es passiert?",
    bugWhenPlaceholder: "z.B. Heute um 14:35",
    bugSend: "Fehlerbericht senden",
    safetyWarning: "⚠️ Diese Option dient ausschließlich zur Meldung kritischer Fehler bei den Sicherheitsfunktionen der App. Im Notfall wähle 112.",
    safetyIssueType: "Was hat nicht funktioniert?",
    safetyDescription: "Beschreibung",
    safetyDescriptionPlaceholder: "Beschreibe was passiert ist...",
    safetyWhen: "Wann ist es passiert?",
    safetySend: "Prioritätsbericht senden",
    featureVote: "Abstimmen",
    featureVoted: "Abgestimmt ✓",
    featureStatusPlanned: "Geplant",
    featureStatusInProgress: "In Bearbeitung 🔥",
    featureStatusCompleted: "Abgeschlossen ✅",
    featureCustomTitle: "Eigene Idee?",
    featureCustomPlaceholder: "Beschreibe deine Idee...",
    featureCustomSend: "Idee einreichen",
    back: "Zurück",
    send: "Senden",
    cancel: "Abbrechen",
    charLeft: "Zeichen übrig",
  },
  es: {
    title: "Soporte",
    responseTime: "Tiempo de respuesta esperado",
    bugTitle: "Reportar un error",
    bugSubtitle: "¿Experimentas un problema técnico?",
    featureTitle: "Solicitar función",
    featureSubtitle: "Vota por las próximas mejoras",
    safetyTitle: "Problema de seguridad",
    safetySubtitle: "Para errores críticos de seguridad",
    faqTitle: "Preguntas frecuentes",
    faqSubtitle: "Respuestas rápidas a preguntas comunes",
    rateTitle: "Valorar MotoGuard",
    rateSubtitle: "Ayuda a otros a encontrar la app",
    contactTitle: "Contacto",
    contactSubtitle: "Envía un email a nuestro equipo",
    bugCategory: "Categoría",
    bugSummary: "Resumen breve",
    bugSummaryPlaceholder: "¿Qué salió mal? (máx 100 caracteres)",
    bugDescription: "Descripción detallada",
    bugDescriptionPlaceholder: "Pasos para reproducir, qué esperabas vs qué ocurrió... (máx 500 caracteres)",
    bugWhen: "¿Cuándo ocurrió?",
    bugWhenPlaceholder: "Ej. Hoy a las 14:35",
    bugSend: "Enviar informe de error",
    safetyWarning: "⚠️ Esta opción es exclusivamente para reportar errores críticos relacionados con las funciones de seguridad de la app. En una emergencia real, llama al 112.",
    safetyIssueType: "¿Qué no funcionó?",
    safetyDescription: "Descripción",
    safetyDescriptionPlaceholder: "Describe lo que ocurrió...",
    safetyWhen: "¿Cuándo ocurrió?",
    safetySend: "Enviar informe prioritario",
    featureVote: "Votar",
    featureVoted: "Votado ✓",
    featureStatusPlanned: "Planificado",
    featureStatusInProgress: "En progreso 🔥",
    featureStatusCompleted: "Completado ✅",
    featureCustomTitle: "¿Tienes tu propia idea?",
    featureCustomPlaceholder: "Describe tu idea de función...",
    featureCustomSend: "Enviar idea",
    back: "Atrás",
    send: "Enviar",
    cancel: "Cancelar",
    charLeft: "caracteres restantes",
  },
  it: {
    title: "Supporto",
    responseTime: "Tempo di risposta previsto",
    bugTitle: "Segnala un bug",
    bugSubtitle: "Stai riscontrando un problema tecnico?",
    featureTitle: "Richiesta funzione",
    featureSubtitle: "Vota i prossimi miglioramenti",
    safetyTitle: "Problema di sicurezza",
    safetySubtitle: "Per bug critici di sicurezza",
    faqTitle: "Domande frequenti",
    faqSubtitle: "Risposte rapide alle domande comuni",
    rateTitle: "Valuta MotoGuard",
    rateSubtitle: "Aiuta altri a trovare l'app",
    contactTitle: "Contattaci",
    contactSubtitle: "Invia un email al nostro team",
    bugCategory: "Categoria",
    bugSummary: "Breve riepilogo",
    bugSummaryPlaceholder: "Cosa non ha funzionato? (max 100 caratteri)",
    bugDescription: "Descrizione dettagliata",
    bugDescriptionPlaceholder: "Passi per riprodurre, cosa ti aspettavi vs cosa è successo... (max 500 caratteri)",
    bugWhen: "Quando è successo?",
    bugWhenPlaceholder: "Es. Oggi alle 14:35",
    bugSend: "Invia segnalazione bug",
    safetyWarning: "⚠️ Questa opzione è esclusivamente per segnalare bug critici relativi alle funzioni di sicurezza dell'app. In un'emergenza reale, chiama il 112.",
    safetyIssueType: "Cosa non ha funzionato?",
    safetyDescription: "Descrizione",
    safetyDescriptionPlaceholder: "Descrivi in dettaglio cosa è successo...",
    safetyWhen: "Quando è successo?",
    safetySend: "Invia segnalazione prioritaria",
    featureVote: "Vota",
    featureVoted: "Votato ✓",
    featureStatusPlanned: "Pianificato",
    featureStatusInProgress: "In corso 🔥",
    featureStatusCompleted: "Completato ✅",
    featureCustomTitle: "Hai un'idea tua?",
    featureCustomPlaceholder: "Descrivi la tua idea di funzione...",
    featureCustomSend: "Invia idea",
    back: "Indietro",
    send: "Invia",
    cancel: "Annulla",
    charLeft: "caratteri rimanenti",
  },
  pt: {
    title: "Suporte",
    responseTime: "Tempo de resposta esperado",
    bugTitle: "Reportar um erro",
    bugSubtitle: "Está a ter um problema técnico?",
    featureTitle: "Solicitar funcionalidade",
    featureSubtitle: "Vote nas próximas melhorias",
    safetyTitle: "Problema de segurança",
    safetySubtitle: "Para erros críticos de segurança",
    faqTitle: "Perguntas frequentes",
    faqSubtitle: "Respostas rápidas às perguntas comuns",
    rateTitle: "Avaliar MotoGuard",
    rateSubtitle: "Ajuda outros a encontrar a app",
    contactTitle: "Contacto",
    contactSubtitle: "Envia um email para a nossa equipa",
    bugCategory: "Categoria",
    bugSummary: "Resumo breve",
    bugSummaryPlaceholder: "O que correu mal? (máx 100 caracteres)",
    bugDescription: "Descrição detalhada",
    bugDescriptionPlaceholder: "Passos para reproduzir, o que esperavas vs o que aconteceu... (máx 500 caracteres)",
    bugWhen: "Quando aconteceu?",
    bugWhenPlaceholder: "Ex. Hoje às 14:35",
    bugSend: "Enviar relatório de erro",
    safetyWarning: "⚠️ Esta opção destina-se exclusivamente a reportar bugs críticos relacionados com as funções de segurança da app. Numa emergência real, liga para o 112.",
    safetyIssueType: "O que não funcionou?",
    safetyDescription: "Descrição",
    safetyDescriptionPlaceholder: "Descreve o que aconteceu em detalhe...",
    safetyWhen: "Quando aconteceu?",
    safetySend: "Enviar relatório prioritário",
    featureVote: "Votar",
    featureVoted: "Votado ✓",
    featureStatusPlanned: "Planeado",
    featureStatusInProgress: "Em progresso 🔥",
    featureStatusCompleted: "Concluído ✅",
    featureCustomTitle: "Tens uma ideia própria?",
    featureCustomPlaceholder: "Descreve a tua ideia de funcionalidade...",
    featureCustomSend: "Submeter ideia",
    back: "Voltar",
    send: "Enviar",
    cancel: "Cancelar",
    charLeft: "caracteres restantes",
  },
};

export const BUG_CATEGORIES: Record<Language, string[]> = {
  en: ["Accident Detection", "Navigation / Map", "Voice Agent", "Emergency / SMS", "Subscription / Payment", "Bluetooth Headset", "App Crash", "Other"],
  hu: ["Balesetdetekció", "Navigáció / Térkép", "Voice Agent", "Vészjelzés / SMS", "Előfizetés / Fizetés", "Bluetooth sisak", "Alkalmazás összeomlás", "Egyéb"],
  de: ["Unfalldetektierung", "Navigation / Karte", "Sprachassistent", "Notfall / SMS", "Abonnement / Zahlung", "Bluetooth-Headset", "App-Absturz", "Sonstiges"],
  es: ["Detección de accidentes", "Navegación / Mapa", "Agente de voz", "Emergencia / SMS", "Suscripción / Pago", "Auricular Bluetooth", "Fallo de la app", "Otro"],
  it: ["Rilevamento incidenti", "Navigazione / Mappa", "Agente vocale", "Emergenza / SMS", "Abbonamento / Pagamento", "Auricolare Bluetooth", "Crash app", "Altro"],
  pt: ["Deteção de acidentes", "Navegação / Mapa", "Agente de voz", "Emergência / SMS", "Subscrição / Pagamento", "Auscultadores Bluetooth", "Falha da app", "Outro"],
};

export const SAFETY_ISSUE_TYPES: Record<Language, string[]> = {
  en: ["Accident detection missed an accident", "Emergency SMS was not sent", "112 call did not start", "False positive (unnecessary alert)", "Other safety issue"],
  hu: ["Accident detection nem észlelt balesetet", "Vészjelző SMS nem ment ki", "112 hívás nem indult el", "False positive (felesleges riasztás)", "Egyéb biztonsági probléma"],
  de: ["Unfalldetektierung hat Unfall nicht erkannt", "Notfall-SMS wurde nicht gesendet", "112-Anruf startete nicht", "Fehlalarm (unnötige Warnung)", "Anderes Sicherheitsproblem"],
  es: ["La detección de accidentes no detectó el accidente", "El SMS de emergencia no se envió", "La llamada al 112 no se inició", "Falso positivo (alerta innecesaria)", "Otro problema de seguridad"],
  it: ["Il rilevamento incidenti non ha rilevato l'incidente", "L'SMS di emergenza non è stato inviato", "La chiamata al 112 non è partita", "Falso positivo (allarme non necessario)", "Altro problema di sicurezza"],
  pt: ["A deteção de acidentes não detetou o acidente", "O SMS de emergência não foi enviado", "A chamada para o 112 não foi iniciada", "Falso positivo (alerta desnecessário)", "Outro problema de segurança"],
};

type MultiLang = Record<Language, string>;

export type FeatureRequest = {
  id: string;
  icon: string;
  title: MultiLang;
  description: MultiLang;
  votes: number;
  status: "planned" | "in_progress" | "completed";
};

export const DEFAULT_FEATURE_REQUESTS: FeatureRequest[] = [
  {
    id: "group_ride", icon: "👥",
    title: { hu: "Csoportos menet", en: "Group Ride Mode", de: "Gruppenfahrt", es: "Modo grupo", it: "Modalità gruppo", pt: "Modo grupo" },
    description: { hu: "Más motorosok valós idejű követése csoportos meneten", en: "Real-time tracking of other riders during group rides", de: "Echtzeit-Tracking anderer Fahrer bei Gruppenfahrten", es: "Seguimiento en tiempo real de otros pilotos en rutas grupales", it: "Tracciamento in tempo reale di altri piloti durante le uscite di gruppo", pt: "Rastreamento em tempo real de outros pilotos durante passeios em grupo" },
    votes: 247, status: "planned",
  },
  {
    id: "weather", icon: "🌦️",
    title: { hu: "Időjárás integráció", en: "Weather Integration", de: "Wetterintegration", es: "Integración meteorológica", it: "Integrazione meteo", pt: "Integração meteorológica" },
    description: { hu: "Menetközbeni időjárás figyelmeztetések hangon", en: "Voice weather alerts during your ride", de: "Sprach-Wetterwarnungen während der Fahrt", es: "Alertas meteorológicas por voz durante tu ruta", it: "Avvisi meteo vocali durante il viaggio", pt: "Alertas meteorológicos por voz durante a viagem" },
    votes: 189, status: "planned",
  },
  {
    id: "service_reminder", icon: "🔧",
    title: { hu: "Szerviz emlékeztető", en: "Service Reminder", de: "Wartungserinnerung", es: "Recordatorio de servicio", it: "Promemoria manutenzione", pt: "Lembrete de manutenção" },
    description: { hu: "Emlékeztető olajcsere, szerviz és gumiabroncs cseréhez km alapján", en: "Reminders for oil change, service, and tire replacement based on km", de: "Erinnerungen für Ölwechsel, Service und Reifenwechsel nach km", es: "Recordatorios de cambio de aceite, servicio y neumáticos por km", it: "Promemoria per cambio olio, revisione e pneumatici in base ai km", pt: "Lembretes de mudança de óleo, revisão e pneus com base em km" },
    votes: 134, status: "planned",
  },
  {
    id: "offline_maps", icon: "🗺️",
    title: { hu: "Offline térkép", en: "Offline Maps", de: "Offline-Karten", es: "Mapas sin conexión", it: "Mappe offline", pt: "Mapas offline" },
    description: { hu: "Térképek letöltése offline használathoz alagutakban és vidéken", en: "Download maps for offline use in tunnels and rural areas", de: "Karten für die Offline-Nutzung in Tunneln und ländlichen Gebieten", es: "Descargar mapas para uso sin conexión en túneles y zonas rurales", it: "Scarica mappe per uso offline in tunnel e aree rurali", pt: "Descarregar mapas para uso offline em túneis e áreas rurais" },
    votes: 312, status: "planned",
  },
  {
    id: "drone_live", icon: "🚁",
    title: { hu: "DJI Drón integráció", en: "DJI Drone Integration", de: "DJI-Drohnen-Integration", es: "Integración dron DJI", it: "Integrazione drone DJI", pt: "Integração drone DJI" },
    description: { hu: "Valós drón vezérlés – Pro+Drone csomagban hamarosan", en: "Live drone control – coming soon in Pro+Drone plan", de: "Live-Drohnensteuerung – demnächst im Pro+Drone-Plan", es: "Control de dron en vivo – próximamente en el plan Pro+Drone", it: "Controllo drone live – presto nel piano Pro+Drone", pt: "Controlo de drone ao vivo – em breve no plano Pro+Drone" },
    votes: 428, status: "in_progress",
  },
];

export type FAQItem = {
  id: string;
  question: MultiLang;
  answer: MultiLang;
};

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: "how_detection",
    question: { hu: "Hogyan működik a balesetdetekció?", en: "How does accident detection work?", de: "Wie funktioniert die Unfalldetektierung?", es: "¿Cómo funciona la detección de accidentes?", it: "Come funziona il rilevamento incidenti?", pt: "Como funciona a deteção de acidentes?" },
    answer: { hu: "Az app a telefon gyorsulásmérőjét és giroszkópját figyeli 10 Hz-en. Ha hirtelen nagy G-erőt érzékel és a sebesség lecsökken, 3 szintű protokollt indít el: figyelmeztetés (15mp), riasztás (30mp), vészjelzés (automatikus SMS).", en: "The app monitors your phone's accelerometer and gyroscope at 10 Hz. If it detects a sudden high G-force and speed drops, it triggers a 3-level protocol: warning (15s), alert (30s), emergency (automatic SMS).", de: "Die App überwacht Beschleunigungsmesser und Gyroskop des Telefons mit 10 Hz. Bei plötzlicher hoher G-Kraft und Geschwindigkeitsabfall wird ein 3-stufiges Protokoll ausgelöst: Warnung (15s), Alarm (30s), Notfall (automatische SMS).", es: "La app monitoriza el acelerómetro y giroscopio del teléfono a 10 Hz. Si detecta una fuerza G alta repentina y caída de velocidad, activa un protocolo de 3 niveles: aviso (15s), alerta (30s), emergencia (SMS automático).", it: "L'app monitora accelerometro e giroscopio del telefono a 10 Hz. Se rileva una forza G elevata improvvisa e calo di velocità, attiva un protocollo a 3 livelli: avviso (15s), allarme (30s), emergenza (SMS automatico).", pt: "A app monitoriza o acelerómetro e giroscópio do telemóvel a 10 Hz. Se detetar uma força G elevada repentina e queda de velocidade, ativa um protocolo de 3 níveis: aviso (15s), alerta (30s), emergência (SMS automático)." },
  },
  {
    id: "false_positive",
    question: { hu: "Mi a teendő ha felesleges riasztást kap a kapcsolatom?", en: "What if my contact receives a false alarm?", de: "Was tun, wenn mein Kontakt einen Fehlalarm erhält?", es: "¿Qué pasa si mi contacto recibe una falsa alarma?", it: "Cosa fare se il mio contatto riceve un falso allarme?", pt: "O que fazer se o meu contato receber um alarme falso?" },
    answer: { hu: "Azonnal hívd fel a kapcsolatodat és jelezd hogy minden rendben van. A visszaszámlálás alatt bármikor törölheted a riasztást a 'Mégse' gombbal vagy a hangerő gombokkal.", en: "Call your contact immediately and let them know you're OK. During the countdown, you can cancel the alert at any time using the 'Cancel' button on screen, or by pressing volume buttons.", de: "Ruf deinen Kontakt sofort an. Während des Countdowns kannst du den Alarm jederzeit mit dem 'Abbrechen'-Button oder den Lautstärketasten abbrechen.", es: "Llama a tu contacto inmediatamente. Durante la cuenta atrás puedes cancelar la alerta en cualquier momento con el botón 'Cancelar' o las teclas de volumen.", it: "Chiama subito il tuo contatto. Durante il conto alla rovescia puoi annullare l'allarme con il pulsante 'Annulla' o i tasti del volume.", pt: "Liga imediatamente para o teu contato. Durante a contagem decrescente podes cancelar o alerta com o botão 'Cancelar' ou as teclas de volume." },
  },
  {
    id: "battery",
    question: { hu: "Mennyire meríti az akkumulátort?", en: "How much does it drain the battery?", de: "Wie stark belastet es den Akku?", es: "¿Cuánto consume la batería?", it: "Quanto consuma la batteria?", pt: "Quanto consome a bateria?" },
    answer: { hu: "Körülbelül 10-15% per óra GPS tracking és balesetdetekció esetén. Ajánlott egy 10 000 mAh-es powerbank hosszú utakhoz.", en: "Approximately 10-15% per hour with GPS tracking and accident detection active. A 10,000 mAh power bank is recommended for long rides.", de: "Ca. 10-15% pro Stunde. Eine 10.000-mAh-Powerbank wird für lange Fahrten empfohlen.", es: "Aproximadamente 10-15% por hora. Se recomienda un power bank de 10.000 mAh para rutas largas.", it: "Circa 10-15% all'ora. Si consiglia un power bank da 10.000 mAh per lunghe percorrenze.", pt: "Aproximadamente 10-15% por hora. Recomenda-se um power bank de 10.000 mAh para viagens longas." },
  },
  {
    id: "cancel_sub",
    question: { hu: "Hogyan mondhatom le az előfizetésemet?", en: "How do I cancel my subscription?", de: "Wie kündige ich mein Abonnement?", es: "¿Cómo cancelo mi suscripción?", it: "Come disdico il mio abbonamento?", pt: "Como cancelo a minha subscrição?" },
    answer: { hu: "iPhone: Beállítások → Apple ID → Előfizetések → MotoGuard → Lemondás. Az előfizetés aktív marad a lemondás dátumáig.", en: "iPhone: Settings → Apple ID → Subscriptions → MotoGuard → Cancel Subscription. Your subscription remains active until the cancellation date.", de: "iPhone: Einstellungen → Apple-ID → Abonnements → MotoGuard → Kündigen.", es: "iPhone: Ajustes → ID de Apple → Suscripciones → MotoGuard → Cancelar.", it: "iPhone: Impostazioni → ID Apple → Abbonamenti → MotoGuard → Annulla.", pt: "iPhone: Definições → ID Apple → Subscrições → MotoGuard → Cancelar." },
  },
  {
    id: "data_privacy",
    question: { hu: "Hova kerülnek az adataim?", en: "Where does my data go?", de: "Wo landen meine Daten?", es: "¿Adónde van mis datos?", it: "Dove vanno i miei dati?", pt: "Para onde vão os meus dados?" },
    answer: { hu: "Sehova. Minden adat (menetnapló, hangparancsok, GPS) kizárólag az eszközödön tárolódik. Nem gyűjtünk, nem tárolunk és nem adunk el semmilyen személyes adatot.", en: "Nowhere. All data (ride history, voice commands, GPS) is stored exclusively on your device. We do not collect, store, or sell any personal data.", de: "Nirgendwo. Alle Daten werden ausschließlich auf deinem Gerät gespeichert. Wir sammeln, speichern oder verkaufen keine persönlichen Daten.", es: "A ningún lado. Todos los datos se almacenan exclusivamente en tu dispositivo. No recopilamos, almacenamos ni vendemos datos personales.", it: "Da nessuna parte. Tutti i dati vengono archiviati esclusivamente sul tuo dispositivo. Non raccogliamo, archiviamo o vendiamo dati personali.", pt: "Em lado nenhum. Todos os dados são armazenados exclusivamente no teu dispositivo. Não recolhemos, armazenamos nem vendemos dados pessoais." },
  },
];
